version: '3.8'

services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongodb-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379" # Host:Container
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
